[package]
name = "markdown_parser"
version = "0.1.0"
edition = "2024"
description = "A simple Markdown parser using pest PEG parse"

[dependencies]
anyhow = "1.0.100"
clap = "4.5.51"
clap_derive = "4.5.49"
pest = "2.8.3"
pest_derive = "2.8.3"
